spring:
  aop:
    proxy-target-class: true
    auto: true
  thymeleaf:
    cache: false
  profiles:
    active: pro
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
baidu:
  address:
    url: http://api.map.baidu.com/geocoding/v3/
    ak: vEe2dQodlX1GvI6L9qRIvf753savFWFt
logging:
  file:
    path: eco_building-log
  level:
    root: info
server:
  port: 9000
