spring:
  datasource:
    url: jdbc:mysql://121.40.87.226:3306/eco_building?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: quant2017
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
upload:
  picture:
    path: D:/eco_building/project_img/
    url: http://121.40.87.226:8200/img/
