DROP TABLE IF EXISTS `project`;
CREATE TABLE `project`  (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `province` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `district` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `street` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `longitude` float NULL DEFAULT NULL,
  `latitude` float NULL DEFAULT NULL,
  `area` double NULL DEFAULT NULL,
  `architectural_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `floor` int(11) NULL DEFAULT NULL,
  `built_time` datetime(0) NULL DEFAULT NULL,
  `photo` longblob NULL,
  `gbes` int(11) NULL DEFAULT NULL,
  `energy_saving_standard` int(11) NULL DEFAULT NULL,
  `whether_to_use_renewabler_esources` int(11) NULL DEFAULT NULL,
  `cooling_mode` int(11) NULL DEFAULT NULL,
  `heating_mode` int(11) NULL DEFAULT NULL,
  `energy_saving_transformation_or_not` int(11) NULL DEFAULT NULL,
  `power_consumption_per_unit_area` decimal(19,2) DEFAULT NULL,
  `water_consumption_per_unit_area` decimal(19,2) DEFAULT NULL,
  `gas_consumption_per_unit_area` decimal(19,2) DEFAULT NULL,
  `created` datetime(0) NOT NULL,
  `del_status` bit(1) NOT NULL DEFAULT b'0',
  `last_modified` datetime(0) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_name` (`name`) USING BTREE,
  INDEX `idx_province` (`province`) USING BTREE,
  INDEX `idx_city` (`city`) USING BTREE,
  INDEX `idx_district` (`district`) USING BTREE,
  INDEX `idx_street` (`street`) USING BTREE,
  INDEX `idx_architectural_type` (`architectural_type`) USING BTREE,
  INDEX `idx_gbes` (`gbes`) USING BTREE,
  INDEX `idx_energy_saving_standard` (`energy_saving_standard`) USING BTREE,
  INDEX `idx_whether_to_use_renewabler_esources` (`whether_to_use_renewabler_esources`) USING BTREE,
  INDEX `idx_cooling_mode` (`cooling_mode`) USING BTREE,
  INDEX `idx_heating_mode` (`heating_mode`) USING BTREE,
  INDEX `idx_energy_saving_transformation_or_not` (`energy_saving_transformation_or_not`) USING BTREE,
  INDEX `idx_area` (`area`) USING BTREE,
  INDEX `idx_built_time` (`built_time`) USING BTREE,
  INDEX `idx_floor` (`floor`) USING BTREE,
  INDEX `idx_power_consumption_per_unit_area` (`power_consumption_per_unit_area`) USING BTREE,
  INDEX `idx_water_consumption_per_unit_area` (`water_consumption_per_unit_area`) USING BTREE,
  INDEX `idx_gas_consumption_per_unit_area` (`gas_consumption_per_unit_area`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
